// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB8bJoOXkvHcqBCvQr-FAEVv9J3FB3V7o',
    appId: '1:207475949801:web:94e85604e8d8a26d08b078',
    messagingSenderId: '207475949801',
    projectId: 'trial-blog-3f020',
    authDomain: 'trial-blog-3f020.firebaseapp.com',
    storageBucket: 'trial-blog-3f020.appspot.com',
    measurementId: 'G-PL63RR2PWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdnEAkgkrlQoLWPTVHjEuvmf6wYoukJoU',
    appId: '1:207475949801:android:cd8a186ea6e6553908b078',
    messagingSenderId: '207475949801',
    projectId: 'trial-blog-3f020',
    storageBucket: 'trial-blog-3f020.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqbOuO1a46nUYIwlpQ2vNqRby06Mmunl8',
    appId: '1:207475949801:ios:c8036839241aa48408b078',
    messagingSenderId: '207475949801',
    projectId: 'trial-blog-3f020',
    storageBucket: 'trial-blog-3f020.appspot.com',
    iosClientId: '207475949801-eikveso53oc3u681mngrt67m1mhb59pd.apps.googleusercontent.com',
    iosBundleId: 'com.example.trailBlog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqbOuO1a46nUYIwlpQ2vNqRby06Mmunl8',
    appId: '1:207475949801:ios:c8036839241aa48408b078',
    messagingSenderId: '207475949801',
    projectId: 'trial-blog-3f020',
    storageBucket: 'trial-blog-3f020.appspot.com',
    iosClientId: '207475949801-eikveso53oc3u681mngrt67m1mhb59pd.apps.googleusercontent.com',
    iosBundleId: 'com.example.trailBlog',
  );
}
